# -*- mode: ruby -*-
# vi: set ft=ruby :


# Example 2
#
# Single box with VirtualBox provider.
#
# NOTE: Make sure you have the precise32 base box installed...
# vagrant box add precise32 http://files.vagrantup.com/precise32.box
#
# VirtualBox modifyvm docs: http://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm
box = {
  :virtualbox => { :name => 'centos/7', :version => '20191013.0.0'},
  :libvirt => { :name => 'generic/ubuntu2010', :version => '1.0.0'}
}

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 8
    libvirt.memory = 8096
  end

  config.vm.define "controller" do |controller|
    controller.ssh.insert_key = false
    controller.vm.synced_folder ".", "/vagrant", id: "v-root", mount_options: ["rw", "tcp", "nolock", "noacl", "async"], type: "nfs", nfs_udp: false
    controller.vm.box = 'generic/ubuntu2010'
    controller.vm.hostname = "master"
    controller.ssh.insert_key = false
    # config.vm.network :forwarded_port, guest: 22, host: 10003, host_ip: "0.0.0.0"
    controller.vm.box_check_update = false
    # controller.vm.network :private_network, ip: "192.168.4.100"
    # config.vm.provision :shell, :privileged => true, :path => "env_proxy_setup.sh"
    controller.vm.provision "shell",inline: <<-SHELL
    # for root ssh self-connect
    sudo mkdir /root/.ssh/
    sudo ssh-keygen -t rsa -P "" -f /root/.ssh/id_rsa
    sudo cat /root/.ssh/id_rsa.pub > /root/.ssh/authorized_keys
    sudo cat /vagrant/ssh_key >> /root/.ssh/authorized_keys

    # sudo cat /vagrant/root_key >> /root/.ssh/authorized_keys
    
    sudo systemctl disable systemd-resolved
    sudo systemctl stop systemd-resolved
    rm -rf /etc/resolv.conf
    echo "nameserver 10.239.27.228" | sudo tee /etc/resolv.conf
    sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
    sudo echo '127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4 master' >/etc/hosts
    sudo echo '::1         localhost localhost.localdomain localhost6 localhost6.localdomain6 master' >>/etc/hosts
    date -s "$(date -d "$(curl -sI baidu.com| grep -i '^date:'|cut -d' ' -f2-)" | xargs -I {} date --date='{}' "+%Y-%m-%d %H:%M:%S")"
    apt update
    apt install nfs-common portmap -y
    ip a   
    SHELL
  end
  # config.vm.define "node1" do |node1|
  #   node1.vm.hostname = "cloud"
  #   node1.vm.box = 'centos/7'
  #   node1.vm.box_check_update = false
  #   node1.ssh.insert_key = false
  #   # node1.vm.network :private_network, ip: "192.168.4.101"
  #   node1.vm.provision "shell",inline: <<-SHELL
  #   # for root ssh self-connect
  #   sudo mkdir /root/.ssh/
  #   sudo ssh-keygen -t rsa -P "" -f /root/.ssh/id_rsa
  #   sudo cat /root/.ssh/id_rsa.pub > /root/.ssh/authorized_keys
  #   sudo cat /vagrant/ssh_key >> /root/.ssh/authorized_keys
  #   sudo cat /vagrant/root_key >> /root/.ssh/authorized_keys
    
  #   sudo systemctl disable systemd-resolved
  #   sudo systemctl stop systemd-resolved
  #   echo "nameserver 10.239.27.228" | sudo tee /etc/resolv.conf
  #   sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
  #   sudo echo '127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4 cloud' >/etc/hosts
  #   sudo echo '::1         localhost localhost.localdomain localhost6 localhost6.localdomain6 cloud' >>/etc/hosts
  #   # date -s "$(date -d "$(curl -sI baidu.com| grep -i '^date:'|cut -d' ' -f2-)" | xargs -I {} date --date='{}' "+%Y-%m-%d %H:%M:%S")"
  #   ip a
  #   SHELL
  # end
  # config.vm.define "node2" do |node2|
  #   node2.vm.hostname = "web"
  #   node2.vm.box = 'centos/7'
  #   node2.vm.box_check_update = false
  #   node2.ssh.insert_key = false
  #   # node2.vm.network :private_network, ip: "192.168.4.102"
  #   node2.vm.provision "shell",inline: <<-SHELL
  #   # for root ssh self-connect
  #   sudo mkdir /root/.ssh/
  #   sudo ssh-keygen -t rsa -P "" -f /root/.ssh/id_rsa
  #   sudo cat /root/.ssh/id_rsa.pub > /root/.ssh/authorized_keys
  #   sudo cat /vagrant/ssh_key >> /root/.ssh/authorized_keys
  #   sudo cat /vagrant/root_key >> /root/.ssh/authorized_keys
    
  #   sudo systemctl disable systemd-resolved
  #   sudo systemctl stop systemd-resolved
  #   echo "nameserver 10.239.27.228" | sudo tee /etc/resolv.conf
  #   sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
  #   sudo echo '127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4 web' >/etc/hosts
  #   sudo echo '::1         localhost localhost.localdomain localhost6 localhost6.localdomain6 web' >>/etc/hosts
  #   # date -s "$(date -d "$(curl -sI baidu.com| grep -i '^date:'|cut -d' ' -f2-)" | xargs -I {} date --date='{}' "+%Y-%m-%d %H:%M:%S")"
  #   ip a
  #   SHELL
  # end
end
